#ifndef QTCONNECTDIALOG_H_
#define QTCONNECTDIALOG_H_

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QGroupBox>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMessageBox>

#include "UIDocument.h"

//First draft generated by QtDesigner

class QtConnectDialog : public QDialog
{
	Q_OBJECT;
	
public:

	QtConnectDialog(QWidget* parent) : QDialog(parent), m_host("localhost"), m_port(FD::UIDocument::DEFAULT_CONNECTION_PORT)
    {
    	setupUi(this);
    	retranslateUi(this);
    }
    ~QtConnectDialog() {}
    
    QString getHost() const
    {
    	return m_host;
    }
    
    int getPort() const
    {
    	return m_port;
    }
    
private:
    QDialogButtonBox *buttonBox;
    QGroupBox *groupBox;
    QLineEdit *lineEdit_host;
    QLineEdit *lineEdit_port;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    
    QString m_host;
    int m_port;
 
private:
    void setupUi(QDialog *Dialog)
    {
	    if (Dialog->objectName().isEmpty())
	        Dialog->setObjectName(QString::fromUtf8("Dialog"));
	    Dialog->resize(264, 191);
	    buttonBox = new QDialogButtonBox(Dialog);
	    buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
	    buttonBox->setGeometry(QRect(90, 150, 161, 32));
	    buttonBox->setOrientation(Qt::Horizontal);
	    buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
	    buttonBox->setCenterButtons(false);
	    groupBox = new QGroupBox(Dialog);
	    groupBox->setObjectName(QString::fromUtf8("groupBox"));
	    lineEdit_host = new QLineEdit(groupBox);
	    lineEdit_host->setObjectName(QString::fromUtf8("lineEdit_host"));
	    lineEdit_host->setGeometry(QRect(60, 30, 158, 28));
	    
	    //Set the default host text
	    lineEdit_host->setText(m_host);
	    
	    lineEdit_port = new QLineEdit(groupBox);
	    lineEdit_port->setObjectName(QString::fromUtf8("lineEdit_port"));
	    lineEdit_port->setGeometry(QRect(60, 70, 61, 28));
	    
	    //Set the default port text
	    lineEdit_port->setText(QString("%1").arg(m_port));
	    
	    lineEdit_port->setMaxLength(5);
	    label = new QLabel(groupBox);
	    label->setObjectName(QString::fromUtf8("label"));
	    label->setGeometry(QRect(20, 30, 31, 28));
	    label_2 = new QLabel(groupBox);
	    label_2->setObjectName(QString::fromUtf8("label_2"));
	    label_2->setGeometry(QRect(20, 70, 28, 28));
	    label_3 = new QLabel(groupBox);
	    label_3->setObjectName(QString::fromUtf8("label_3"));
	    label_3->setGeometry(QRect(130, 70, 150, 28));
	
	    retranslateUi(Dialog);
	    QObject::connect(buttonBox, SIGNAL(accepted()), this, SLOT(accept()));
	    QObject::connect(buttonBox, SIGNAL(rejected()), this, SLOT(reject()));
	
	    QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
	    Dialog->setWindowTitle(QApplication::translate("Dialog", "Remote document", 0, QApplication::UnicodeUTF8));
	    groupBox->setTitle(QApplication::translate("Dialog", "Connect to a document", 0, QApplication::UnicodeUTF8));
	    label->setText(QApplication::translate("Dialog", "Host :", 0, QApplication::UnicodeUTF8));
	    label_2->setText(QApplication::translate("Dialog", "Port :", 0, QApplication::UnicodeUTF8));
	    label_3->setText(QApplication::translate("Dialog", "(49152 through 65535)", 0, QApplication::UnicodeUTF8));
	    Q_UNUSED(Dialog);
    } // retranslateUi
    
    bool validateForm()
    {
    	QString host = lineEdit_host->text();
		int port = lineEdit_port->text().toInt();
		if(host.isEmpty() || port < 49152 || port > 65535)
		{
			QString msg;
			if(host.isEmpty()) {
				msg.append(tr("-The host is empty.\n"));
			}
			if(port < 49152 || port > 65535) {
				msg.append(tr("-The port is invalid."));
			}
			QMessageBox::warning(this, tr("Error"), msg, QMessageBox::Ok);
			return false;
		}
		else
		{
			m_host = host;
			m_port = port;
		}
    	return true;
    }

public slots:
    virtual void accept()
    {
    	if(validateForm()) {
    		QDialog::accept();
    	}
    }
    
    virtual void reject()
    {
    	lineEdit_host->setText(m_host);
		lineEdit_port->setText(QString("%1").arg(m_port));
		QDialog::reject();
    }
};

#endif /*QTCONNECTDIALOG_H_*/
