/* Automatically generated by po2tbl.sed from VFlow.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
};

int _msg_tbl_length = 1;
