#ifndef LAPACKFLOW_H
#define LAPACKFLOW_H

#include "fortran.h"
#include <iostream>

//SUBROUTINE_F77 solve_(INTEGER &N, INTEGER &NRHS, REAL* A, REAL *B, INTEGER &INFO);

SUBROUTINE_F77 solve_(INTEGER &N, INTEGER &NRHS, REAL* A, REAL *B, REAL* X);
SUBROUTINE_F77 solvels_(INTEGER &M, INTEGER &N, INTEGER &NRHS, REAL* A, REAL* BX);
SUBROUTINE_F77 eig_(INTEGER &N, REAL* A, REAL *D, REAL* V);
SUBROUTINE_F77 svd_(INTEGER &M, INTEGER &N, REAL* A, REAL* U, REAL *S, REAL *VT);


#endif
